/**
 * Menu fixé et transparent - http://www.webinventif.fr/barre-de-navigation-fixe-depliable-et-transparente/
 * 
 * Copyright (c) 2008 Julien Chauvin (webinventif.fr)
 * Licensed under the Creative Commons License:
 * http://creativecommons.org/licenses/by/3.0/
 *
 * Date: 2008-02-25
 */
function fixed_bottom(select,offS){return Number(-offS+document.documentElement.clientHeight-select.offsetHeight+document.documentElement.scrollTop+document.body.scrollTop)+'px';}$(document).ready(function(){$("#magicmenu").show();if($.browser.msie){if($.browser.version=="6.0"){$("#magicmini").hide();$("#magicmaxi").hide();$("#magicbox").css('position','absolute');}else if($.browser.version=="7.0"){$("#magicbox").css('position','fixed');$("#magicmini").hide();$("#magicmaxi").hide();}}else{$("#magicbox").css('position','fixed');$("#magicmini").hide();$("#magicmaxi").hide();}$("#magicmenu .m.close").click(function(){$.cookie('selectmenu','close',{path:'/'});$("#magiccontent").slideUp("slow",function(){$("#magicmaxi").hide();$("#magicmini").hide();$(this).show();});toggleselect(this);return false;});$("#magicmenu .m.menu").click(function(){$.cookie('selectmenu','light',{path:'/'});if($("#magicmini").css("display")=="none"&&$("#magicmaxi").css("display")=="none"){$("#magiccontent").hide();$("#magicmini").show();}if($("#magiccontent").css("display")=="none"){$("#magicmaxi").hide();$("#magiccontent").slideDown("slow");}else if($("#magicmaxi").css("display")=="block"){$("#magicmaxi").slideUp("slow");}toggleselect(this);return false;});$("#magicmenu .m.login").click(function(){$.cookie('selectmenu','full',{path:'/'});if($("#magicmini").css("display")=="none"&&$("#magicmaxi").css("display")=="none"){$("#magiccontent").hide();$("#magicmini").show();}if($("#magiccontent").css("display")=="none"){$("#magicmaxi").show();$("#magiccontent").slideDown("slow");}else if($("#magicmaxi").css("display")=="none"){$("#magicmaxi").slideDown("slow");}toggleselect(this);return false;});$("#magiccontent").fadeTo("fast",1.0);$("#magicmenu ul li a").each(function(i){$(this).fadeTo("fast",1.0);this.colback=$(this).css('background-color');this.tempcol=false;$(this).hover(function(){$(this).css('background-color',$("#magiccontent").css('background-color'))},function(){if(this.tempcol){$(this).css('background-color',$("#magiccontent").css('background-color'));}else{$(this).css('background-color',this.colback);}});});function toggleselect(ele){$("#magicmenu ul li a").each(function(i){$(this).css('background-color',this.colback);this.tempcol=false;});$(ele).css('background-color',$("#magiccontent").css('background-color'));ele.tempcol=true;}if($.cookie('selectmenu')){if($.cookie('selectmenu')=="full"){$("#magicmini").show();$("#magicmaxi").show();$("#magicmenu .m.login").each(function(){toggleselect(this);});}else if($.cookie('selectmenu')=="light"){$("#magicmini").show();$("#magicmenu .m.menu").each(function(){toggleselect(this);});}else if($.cookie('selectmenu')=="close"){$("#magicmenu .m.close").each(function(){toggleselect(this);});}}else{$("#magicmini").show();toggleselect("#magicmenu .m.menu");}});